### ISSUE TITLE
Consider change url submodule from ssh to https

### ISSUE THREAD

**Issue by rstm-sf** [rmboggs/DocxToSource#10]
Hello! Consider change url submodule from ssh to https

https://github.com/rmboggs/DocxToSource/blob/master/.gitmodules#L3

it is not convenient for new users

Workaround:
 in root directory
```sh
git config submodule."src/Serialize.OpenXml.CodeGen".url https://github.com/rmboggs/Serialize.OpenXml.CodeGen.git
```

**Comment by rmboggs** [comment]
Yeah, your right.  I'll see if I can fix this when I get back from vacation, sometime next week.

**Comment by rmboggs** [comment]
Should be good now....

**Comment by rstm-sf** [comment]
https://github.com/rmboggs/DocxToSource/commit/36399ce7b84cb141fb62e4baf393afd0c3c73901
