### ISSUE TITLE
Application crashes when trying to open a file with embedded documents

### ISSUE THREAD

**Issue by Arimov** [rmboggs/DocxToSource#5]
If I create an MS Word file (MS Word 2016) with another MS Word file embedded in it, 
and try to open it in the application, the application crashes without reporting an error

**Comment by rmboggs** [comment]
Marking this as needs confirmation, meaning that I need to reproduce the issue on my side so I know how to fix.

**Comment by rmboggs** [comment]
Hi,
I just tried this and the application is acting as expected, no crashing.  Do you have a sample document that reliably recreates the issue that I can use?

**Comment by Arimov** [comment]
Now I tried to reproduce the situation, but this time everything works fine.  Maybe the last time was due to a certain condition of my computer (lack of memory or something else). Now I can not get this effect

**Comment by Arimov** [comment]
Now I got a similar effect when I had a document already open in MS Word (maybe the previous time this happened too), it would be good to get a warning in that case, that the document is already open in a different application
